---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It
#words: SUBJECT!!!

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
#words: verb

---
spring:
  profiles: article
words: a,the
#words: article

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
#words: adjective

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
#words: noun